"""
VendorBridge ERP – Alembic Migration Environment
==================================================
Configures Alembic to use the application's SQLAlchemy Base metadata
for autogenerated migrations.
"""

from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool
from alembic import context

# ── Import Base and all models so metadata is populated ───────────
# This import triggers app/models/__init__.py which registers
# every model class on Base.metadata.
from app.database import Base
import app.models  # noqa: F401  — side-effect import

# ── Alembic Config object ────────────────────────────────────────
config = context.config

# Interpret the config file for Python logging.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Set the target metadata for autogenerate support.
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """
    Run migrations in 'offline' mode.

    Generates SQL scripts without connecting to the database.
    """
    # TODO: Implement offline migration runner
    #   1. Get the sqlalchemy.url from alembic.ini config
    #   2. Call context.configure(
    #          url=url,
    #          target_metadata=target_metadata,
    #          literal_binds=True,
    #          dialect_opts={"paramstyle": "named"},
    #      )
    #   3. with context.begin_transaction():
    #          context.run_migrations()
    pass


def run_migrations_online() -> None:
    """
    Run migrations in 'online' mode.

    Creates an engine and associates a connection with the context.
    """
    # TODO: Implement online migration runner
    #   1. Create engine via engine_from_config(
    #          config.get_section(config.config_ini_section, {}),
    #          prefix="sqlalchemy.",
    #          poolclass=pool.NullPool,
    #      )
    #   2. with connectable.connect() as connection:
    #          context.configure(
    #              connection=connection,
    #              target_metadata=target_metadata,
    #          )
    #          with context.begin_transaction():
    #              context.run_migrations()
    pass


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
